name: Release GHCR Package

on:
  push:
    tags:
      - 'V*'

jobs:
  ghcr:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=match,pattern=V(.*),group=1
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: get tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            LATEXINDENT_VERSION=${{ env.TAG }}
